# Generated by Django 5.2.5 on 2025-09-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalcare', '0002_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Optional profile image (avatar).', null=True, upload_to='profiles/'),
        ),
    ]
